Add E2E test for converting boolean type to text type
centerofci/mathesar pull request #1182
Opened 2022-03-16 11:37 UTC by sahilsaini110

Fixes #1127 

Added E2E test to convert col type from boolean to text type.
**Technical details**

**Screenshots**

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-03-16 13:25 UTC, sahilsaini110 commented
''' statement = "\n            SELECT c.oid\n            FROM pg_catalog.pg_class c\n            LEFT JOIN pg_catalog.pg_namespace n O...(c.oid))\n            AND c.relname = %(table_name)s AND c.relkind in\n            ('r', 'v', 'm', 'f', 'p')\n        "
parameters = {'table_name': 'pg_namespace'}
context = <sqlalchemy.dialects.postgresql.psycopg2.PGExecutionContext_psycopg2 object at 0x7f7697b222b0>

    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
E       server closed the connection unexpectedly
E               This probably means the server terminated abnormally
E               before or while processing the request.
E       
E       [SQL: 
E                   SELECT c.oid
E                   FROM pg_catalog.pg_class c
E                   LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
E                   WHERE (pg_catalog.pg_table_is_visible(c.oid))
E                   AND c.relname = %(table_name)s AND c.relkind in
E                   ('r', 'v', 'm', 'f', 'p')
E               ]
E       [parameters: {'table_name': 'pg_namespace'}]
E       (Background on this error at: http://sqlalche.me/e/14/e3q8)

/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py:717: OperationalError
____________________ ERROR at setup of test_tabs[chromium] _____________________

self = Engine(postgresql://mathesar:***@mathesar_db/mathesar_db_test)
fn = <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f76afd938e0>>
connection = None

    def _wrap_pool_connect(self, fn, connection):
        dialect = self.dialect
        try:
>           return fn()

/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3211: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sqlalchemy.pool.impl.QueuePool object at 0x7f76afd938e0>

    def connect(self):
        """Return a DBAPI connection from the pool.
    
        The connection is instrumented such that when its
        ``close()`` method is called, the connection will be returned to
        the pool.
    
        """
>       return _ConnectionFairy._checkout(self)

/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py:307: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'sqlalchemy.pool.base._ConnectionFairy'>
pool = <sqlalchemy.pool.impl.QueuePool object at 0x7f76afd938e0>
threadconns = None, fairy = None

    @classmethod
    def _checkout(cls, pool, threadconns=None, fairy=None):
        if not fairy:
>           fairy = _ConnectionRecord.checkout(pool)

/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py:767: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'sqlalchemy.pool.base._ConnectionRecord'>
pool = <sqlalchemy.pool.impl.QueuePool object at 0x7f76afd938e0>

    @classmethod
    def checkout(cls, pool):
        rec = pool._do_get()
        try:
            dbapi_connection = rec.get_connection()
        except Exception as err:
            with util.safe_reraise():
>               rec._checkin_failed(err, _fairy_was_created=False)

/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py:430: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sqlalchemy.util.langhelpers.safe_reraise object at 0x7f7697ba8940>
type_ = None, value = None, traceback = None

    def __exit__(self, type_, value, traceback):
        # see #2703 for notes
        if type_ is None:
            exc_type, exc_value, exc_tb = self._exc_info
            self._exc_info = None  # remove potential circular references
            if not self.warn_only:
>               compat.raise_(
                    exc_value,
                    with_traceback=exc_tb,
                )

/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py:70: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def raise_(
        exception, with_traceback=None, replace_context=None, from_=False
    ):
        r"""implement "raise" with cause support.
    
        :param exception: exception to raise
        :param with_traceback: will call exception.with_traceback()
        :param replace_context: an as-yet-unsupported feature.  This is
         an exception object which we are "replacing", e.g., it's our
         "cause" but we don't want it printed.    Basically just what
         ``__suppress_context__`` does but we don't want to suppress
         the enclosing context, if any.  So for now we make it the
         cause.
        :param from\_: the cause.  this actually sets the cause and doesn't
         hope to hide it someday.
    
        """
        if with_traceback is not None:
            exception = exception.with_traceback(with_traceback)
    
        if from_ is not False:
            exception.__cause__ = from_
        elif replace_context is not None:
            # no good solution here, we would like to have the exception
            # have only the context of replace_context.__context__ so that the
            # intermediary exception does not change, but we can't figure
            # that out.
            exception.__cause__ = replace_context
    
        try:
>           raise exception

/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py:207: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'sqlalchemy.pool.base._ConnectionRecord'>
pool = <sqlalchemy.pool.impl.QueuePool object at 0x7f76afd938e0>

    @classmethod
    def checkout(cls, pool):
        rec = pool._do_get()
        try:
>           dbapi_connection = rec.get_connection()

/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py:427: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sqlalchemy.pool.base._ConnectionRecord object at 0x7f76ae6160d0>

    def get_connection(self):
        recycle = False
    
        # NOTE: the various comparisons here are assuming that measurable time
        # passes between these state changes.  however, time.time() is not
        # guaranteed to have sub-second precision.  comparisons of
        # "invalidation time" to "starttime" should perhaps use >= so that the
        # state change can take place assuming no measurable  time has passed,
        # however this does not guarantee correct behavior here as if time
        # continues to not pass, it will try to reconnect repeatedly until
        # these timestamps diverge, so in that sense using > is safer.  Per
        # https://stackoverflow.com/a/1938096/34549, Windows time.time() may be
        # within 16 milliseconds accuracy, so unit tests for connection
        # invalidation need a sleep of at least this long between initial start
        # time and invalidation for the logic below to work reliably.
        if self.connection is None:
            self.info.clear()
>           self.__connect()

/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py:552: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sqlalchemy.pool.base._ConnectionRecord object at 0x7f76ae6160d0>

    def __connect(self):
        pool = self.__pool
    
        # ensure any existing connection is removed, so that if
        # creator fails, this attribute stays None
        self.connection = None
        try:
            self.starttime = time.time()
            connection = pool._invoke_creator(self)
            pool.logger.debug("Created new connection %r", connection)
            self.connection = connection
            self.fresh = True
        except Exception as e:
            with util.safe_reraise():
>               pool.logger.debug("Error on connect(): %s", e)

/usr/local/li [...]

2022-03-16 13:33 UTC, pavish commented
@sahilsaini110 Since this PR isn't fully ready, I'm marking it as a draft. Feel free to @ anyone directly for help.

2022-03-16 14:27 UTC, ManishShah120 commented
> @ManishShah120 may you please help me with this issue

Ok, trying.

2022-03-16 14:40 UTC, ManishShah120 commented on mathesar/tests/integration/test_columns.py
> +    page.locator(".dropdown .container .section .btn:has-text('Text')")
```
def test_convert_boolean_col_to_text_col(page, patent_schema, base_schema_url):
```
pass `patent_schema` as the argument.

2022-03-16 14:41 UTC, ManishShah120 requested changes
Things look good, could you try doing the above suggestion once. In my case after doing the changes it worked, i.e., the test passed but the column didn't got converted though.

2022-03-16 15:10 UTC, ManishShah120 commented on mathesar/tests/integration/conftest.py
> +    return f"{live_server}/{patent_schema.database.name}/{patent_schema.id}"
I didn't do these changes too, so try once undoing it.

2022-03-16 16:39 UTC, sahilsaini110 commented
Hello @ManishShah120 I have tried the above changes but still errors are there.

2022-03-18 06:28 UTC, silentninja commented
@sahilsaini110 #1168 should solve the issue you are facing. I will mark this issue as blocked until #1168 is fixed

2022-03-25 21:06 UTC, kgodey commented
This should be unblocked now.

2022-04-03 05:28 UTC, kgodey commented
@sahilsaini110 I'm following up since it's been a few days since this PR was updated, are you still working on this?

2022-04-08 13:23 UTC, sahilsaini110 commented
> @sahilsaini110 I'm following up since it's been a few days since this PR was updated, are you still working on this?

yes I am, will try to resolve all the checks and put them for review again.

2022-04-09 03:22 UTC, sahilsaini110 commented
@ManishShah120 may you please check why still this check is failing.

2022-04-28 07:26 UTC, sahilsaini110 commented
I'm closing this pull request and starting a new one because this one has a lot of commits and is causing unnecessary work to be messed up.

2022-04-28 07:26 UTC, closed without merging