[1177] - Strip column names before adding in DB
centerofci/mathesar pull request #1201
Opened 2022-03-20 14:36 UTC by muhsinkamil

Fixes https://github.com/centerofci/mathesar/issues/1177

**Technical details**

**Screenshots**

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-03-22 06:20 UTC, kgodey requested changes
@muhsinkamil This code looks fine to me, thanks for the contribution! Could you please add a test or two for the functionality?

2022-03-22 08:23 UTC, muhsinkamil commented
Thank you @kgodey, I will look into it.

2022-03-24 15:58 UTC, muhsinkamil commented
@kgodey Sorry, I was waiting for action to be complete. But it's been going on forever 😞

2022-03-25 02:27 UTC, kgodey approved these changes
Looks great @muhsinkamil! Please fix linting errors and this can be merged.

2022-03-25 02:27 UTC, kgodey commented on mathesar/tests/data/col_names_with_spaces.csv
> +2,"baz","bam"
Please add newline at the end of the file.

2022-03-25 11:11 UTC, merged