Issue#1214
centerofci/mathesar pull request #1387
Opened 2022-05-18 20:40 UTC by Cronus1007

Fixes #1214 

**Technical details**
Initial setup of the python class to represent 'name' db Type
**Screenshots**

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-05-23 08:13 UTC, mathemancer requested changes
Thanks for your work on this so far. 

We shouldn't keep two versions of `NAME` around (i.e., `NAME` and `MATHESAR_NAME`. The goal is to replace the default SQLAlchemy implementation of the `NAME` type with ours.

2022-05-23 08:13 UTC, mathemancer commented on db/types/base.py
>      NAME = 'name'
Only one of `MATHESAR_NAME` or `NAME` should remain.

2022-05-23 08:13 UTC, mathemancer commented on db/types/operations/cast.py
> +MATHESAR_NAME = base.PostgresType.MATHESAR_NAME.value
Same here. We shouldn't have both. We want to replace the default `"name"` implementation with ours (mainly in the `ischema_names` dict).

2022-05-24 20:47 UTC, Cronus1007 commented
@mathemancer Closing #1387 for now since #1222 introduced a lot of merge conflicts so I would like to have a fresh start with the changes u suggested.

2022-05-24 20:47 UTC, closed without merging

2022-05-25 05:43 UTC, mathemancer commented
@Cronus1007 Sorry for the confusion on this. Please let us know if there's any problem trying to reorganize with the new structure.

2022-05-25 05:51 UTC, Cronus1007 commented
@mathemancer Sure.