API and UI for configuring number of digits to display on numbers
centerofci/mathesar pull request #1402
Opened 2022-05-27 18:31 UTC by seancolsen

Fixes #1332

## Before

- The number of digits displayed for a number is always taken from the number of digits in that number's numerical value. There is no way to format `1` as `1.00`, for example. And no way to format `1.119999999` as `1.12`.

## After

- The back end and API supports two display options for numbers:

    - `minimum_fraction_digits`
    - `maximum_fraction_digits`

    Why two separate options? See use-case "(C)" in the [ticket](https://github.com/centerofci/mathesar/issues/1332).

- The Postgres `scale` value for `NUMERIC` numbers is _not_ used to format the number of decimal places. A benefit to this approach is that we can format other Postgres types like `DOUBLE PRECISION`.

- If the value of a number has more decimal places than the formatting allows, it will be rounded during formatting, and the full value will be visible while editing.

## Demo

https://www.loom.com/share/ddd468c2c40e42d190632e56676e8827

## Notes

- The UI implemented here does not address use-case "(C)" in the [ticket](https://github.com/centerofci/mathesar/issues/1332). I have opened #1401 for that purpose.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-05-27 18:32 UTC, seancolsen commented
This is a full-stack PR, so I've assigned @silentninja to review the back end (because this feature is in the data types milestone), and @pavish to review the front end.

2022-05-31 08:43 UTC, silentninja requested changes
Looks good to me. Got a few minor changes which I have commented on below.

2022-05-31 18:27 UTC, seancolsen commented on mathesar/api/serializers/shared_serializers.py
> +            raise serializers.ValidationError(
Right. Thanks! This should be fixed in 3c978af758ec50674015e52cf0df328f03835543

2022-05-31 18:27 UTC, seancolsen commented
@silentninja this is ready for re-review.

2022-06-06 07:49 UTC, pavish approved these changes
@seancolsen Looks great to me!

I think having `Decimal places` in both type options and display options would be quite confusing to the user. I'd lean towards removing `Decimal places` and `Max digits` type options entirely on the frontend (scale and precision).

2022-06-06 07:50 UTC, merged

2022-06-06 12:01 UTC, seancolsen commented
@pavish 

> I think having Decimal places in both type options and display options would be quite confusing to the user.

Agreed. I've opened #1420 for this.