Mathesar 946 record preview data
centerofci/mathesar pull request #1404
Opened 2022-05-30 00:01 UTC by silentninja

Fixes #946 

Adds an additional field `previews` to `/records/` API which contains the preview data for the foreign key columns.

**Technical Details**

New API response for `/records/`

```
{
  "count": 1393,
  "grouping": {
  },
  "previews": {
    "1": {
      "1": {
        "1": "NASA Goddard Space Flight Center"
      },
      "2": {
        "1": "NASA Ames Space Flight Center"
      },
      "3": {
        "1": "NASA Kennedy Space Flight Center"
      }
    },
   "2": {
      "1": {
        "1": "Boston"
      },
  },
  "results": [
    {
      "0": 1,
      "1": 1, // NASA Goddard Space Flight Center
      "2": null,
      "3": 2,
      "4": "KSC-12871"
    },
    {
      "0": 2,
      "1": 2,
      "2": 2, // Boston
      "3": 1,
      "4": "KSC-12872"
    },
    {
      "0": 3,
      "1": 3,
      "2": 2,
      "3": 2,
      "4": "KSC-12873"
    }
  ]
}
```

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-07-14 08:47 UTC, mathemancer requested changes
Please consider using joins to add the preview data in. It would be more idiomatic, and also brings performance benefits.

2022-07-14 08:47 UTC, mathemancer commented on db/records/operations/select.py
> +    return preview_filters
You should try using a join for this. It will be more readable and performant.

2022-07-14 14:49 UTC, mathemancer approved these changes
After a call with @silentninja , I agree we should get this merged in, then work out any performance issues or other changes later.

2022-07-21 06:24 UTC, mathemancer commented
@dmos62 's PR merged right before my approving review. Thus, @silentninja needs to sort out some merge conflicts before we can get this merged to master.

2022-07-21 12:17 UTC, silentninja commented
I am going to make the changes to the API just as we discussed. 

```json5
//Example schema
{
  "count": 1393,
  "grouping": {},
  "previews_render": [
    {
      "column": 10 // "Items"."Id",
      "template": "{10}"
    },
    {
      "column": 20 // "Items"."Acquisition Date",
      "template": "{20}"
    }
    {
      "column": 100, // "Items"."Publication Id" colum ID
      
      // The Publications summary template: "Title: {278}, Author: {279}"
      // The Authors summary template is: "{280} {281}"
      //
      // We use both those values to form the following template, putting the Authors
      // template inside the Publications template.
      "template": "Title: {278}, Author: {280&1} {281&1} Secondary Author: {280&2}",
      "data": [{"value" 23", "278": "Blink", "280&1": "Malcom", "281&1": "Gladwell", "280&2": "Sally"}]
  "results": [
    {"10": 1, "20": 3.50, "100": 23},
  ]
  
}
```

The field names might change, but the schema should remain the same

2022-08-16 16:25 UTC, mathemancer approved these changes
I think this looks good to merge. I'll try to submit a PR at some point that uncomments some tests once the data explorer bug is fixed.

2022-08-16 16:53 UTC, merged