Table dependents graph tests
centerofci/mathesar pull request #1478
Opened 2022-07-25 15:10 UTC by Jyuart

Fixes #[issue number]

**Technical details**

**Screenshots**

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-08-08 10:20 UTC, silentninja requested changes
Nice work! @Jyuart. Overall the PR looks good, but there are a few changes that need to be addressed before we get this merged.

1. Pytest gets confused with `mathesar/api/tests/api/test_dependents.py` and  `db/tests/tables/test_dependents.py` as they both have the same name. Please rename the API test file to `mathesar/api/tests/api/test_dependents_api.py`

2. Move the `dependency_graph related` files in the DB library into a separate module instead of having them inside the tables module because they are applicable for other DB objects too.

2022-08-08 18:51 UTC, Jyuart commented on db/dependents_utils.py
> +    metadata = MetaData()
Updated it to use a single metadata per a single calling function. I have two here now: for getting a dependents graph and for checking if dependents exist for a specific object

2022-08-15 18:15 UTC, silentninja commented
Looks good! Thanks for the PR @Jyuart

2022-08-15 19:15 UTC, silentninja approved these changes

2022-08-15 19:15 UTC, merged