add json array sorting tests
centerofci/mathesar pull request #1482
Opened 2022-07-26 04:15 UTC by Jinxiao0302

Related to #1411 

This PR creates a testing table with a column of json array type, and test cases for json array sorting behavior.

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-07-27 02:48 UTC, mathemancer requested changes
First, please use our custom JSON array type for the table so it's clear what the goals of the test are. Also, please add some nested structures to the test data so we can show how they sort as well. Finally, I think you should specify the entire expected array so that whoever is reading your test in the future can reason through the rule set for sorting this type.

2022-07-27 05:44 UTC, Jinxiao0302 commented
> First, please use our custom JSON array type for the table so it's clear what the goals of the test are. Also, please add some nested structures to the test data so we can show how they sort as well. Finally, I think you should specify the entire expected array so that whoever is reading your test in the future can reason through the rule set for sorting this type.

Thanks for your reviews. I have made changes to the code following the instructions. 
For the nested arrays, the nested arrays come later than other types of elements when compared. When comparing among nested arrays,  the same rule of outer array ordering is used.

2022-07-27 08:19 UTC, mathemancer requested changes
See my specific suggestion. Good work so far!

2022-07-27 08:19 UTC, mathemancer commented on db/tests/records/operations/test_sort.py
> +        and record_list[12][0] == 5 and record_list[13][0] == 3
The goals of this test should be both checking the behavior, but also providing an example of how sorting will look.

```suggestion
    assert [row["json_array"] for row in record_list] == [
        '[]',
        '["BMW", "Ford", "Fiat"]',
        '["BMW", "Ford", [1, 2]]',
        '["BMW", "Ford", ["Akshay", "Prashant", "Varun"]]',
        '["BMW", "Ford", [1, 2, 3]]',
        '["Ford", "BMW", "Fiat"]',
        '[1, 2, 3]',
        '[1, 2, false]',
        '[1, 2, true]',
        '[2, 3, 4]',
        '[false, false, false]',
        '[true, true, false]',
        '["BMW", "Ford", "Fiat", "Fiat"]',
        '["Ram", "Shyam", "Radhika", "Akshay", "Prashant", "Varun"]',
    ]
```

Please double-check my ordering and types for the suggestion. I hope it makes clear how the test should look, though.

2022-07-28 03:09 UTC, mathemancer approved these changes
This looks great. Thanks @Jinxiao0302 !

2022-07-28 03:33 UTC, merged