Invalidate type_options having precision without a scale
centerofci/mathesar pull request #2033
Opened 2022-12-07 13:22 UTC by Anish9901

Fixes #1367 

Setting a precision parameter of the type_options without a valid scale could result in data loss so we disallow having precision without a scale. 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-12-09 03:14 UTC, mathemancer requested changes
Looks good overall. I did make a suggestion in a specific comment. Please consider it.

2022-12-09 06:46 UTC, Anish9901 commented on mathesar/api/serializers/columns.py
> +        ):
You are right it's an xor, I should have noticed that.

2022-12-13 03:35 UTC, mathemancer approved these changes
Okay, this looks good to me. Thanks!

2022-12-13 03:48 UTC, kgodey commented
This won't auto-merge due to merge conflicts @Anish9901 @mathemancer

2022-12-13 03:59 UTC, mathemancer commented
Thanks for the heads-up @kgodey

2022-12-13 04:22 UTC, merged