Fix duplicate schema bug
centerofci/mathesar pull request #266
Opened 2021-06-16 21:22 UTC by eito-fis

Fixes #206 

Prevents the schema creation endpoint from making duplicate schemas.

**Technical details**
Adds a validation function to the `SchemaSerializer` that ensures another schema in the same database with the same name doesn't already exist. Also updates the `SchemaViewSet` to check if the request data is valid before creating a new schema.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-06-18 14:34 UTC, kgodey requested changes
One small change requested.

I switched the base branch to `db_syncing` to make this easier to review. I'll label the PR as blocked so we know not to merge it yet.

2021-06-18 14:34 UTC, kgodey commented on mathesar/serializers.py
> +        existing = [schema for schema in Schema.objects.all()
I think it would be better to use the list of schema names from the `db` module here, since the database is the source of truth for schema names.

2021-06-18 23:10 UTC, eito-fis commented
Updated to run validation inside the `create_schema_and_object()` function instead of the serializer so we have access to an engine. Now checks name against the list of names returned from `get_mathesar_schemas()` instead of django's `Schema` queryset.

An alternative (and maybe more performant?) approach could be trying to reflect the schema, and only continuing on error. It does seem a bit hacky though, so I went with `get_mathesar_schemas()`. Happy to change it if this would be preferred.

2021-06-21 15:46 UTC, kgodey approved these changes
@eito-fis I think the approach you took looks good. Please merge in the latest `db_syncing` to fix merge conflicts.

2021-06-21 20:03 UTC, merged