Update README.md with troubleshooting instructions
centerofci/mathesar pull request #2751
Opened 2023-03-27 13:20 UTC by dmos62

Stemming from conversation in Matrix about instructing new contributors to use issue trackers for troubleshooting more.

Goal is to make Matrix the last go-to for troubleshooting, or in other words funnel more of the troubleshooting into searchable platforms like Github or StackOverflow, so as to reduce repetitive troubleshooting sessions in Matrix.

If this is merged, might make sense to link to this in our contributor and/or gsoc candidate guides.

2023-03-27 13:22 UTC, dmos62 commented
@kgodey asking for your review since I'm not sure who's responsibility README falls under. @pavish asking for your review since we discussed something along these lines.

2023-03-28 18:12 UTC, pavish commented on README.md
> +4. If you think this is a novel problem, ask on one of those platforms or [on Matrix](#join-our-community)
I think it might be better if the default goto action for novel problems is to open tickets instead of matrix chats.

2023-03-28 18:13 UTC, pavish reviewed
@dmos62 I think this sounds good, I had a suggestion. I'll defer to @kgodey to review and approve the PR.

2023-03-28 19:06 UTC, kgodey requested changes
Please see in-line comment.

2023-03-28 19:06 UTC, kgodey commented on README.md
> +4. If you think this is a novel problem, ask on one of those platforms or [on Matrix](#join-our-community)
I agree with @pavish, an issue is much preferable to a Matrix chat. 

Also, I think this belongs in our wiki contributing guide, not in the README. Our README serves a wide audience and the goals are to provide an introduction to the project and to link out to appropriate resources for various sub-groups (contributors, users, people evaluating us, etc.) If we put primary documentation here, it will end up becoming long and unwieldy.

2023-03-29 09:15 UTC, dmos62 commented on README.md
> +4. If you think this is a novel problem, ask on one of those platforms or [on Matrix](#join-our-community)
> If you think this is a novel problem, ask on one of those platforms or on Matrix

This does instruct asking on the other platforms first and Matrix second. We can uncollapse "those platforms" so that it's something like:

```suggestion
4. If you think this is a novel problem, ask on [our issue tracker](https://github.com/centerofci/mathesar/issues/), [StackOverflow](https://stackoverflow.com/questions/tagged/mathesar), or [on Matrix](#join-our-community)
```

Another option could be to split asking on Matrix as a 5th step that says something like:
```suggestion
4. If you think this is a novel problem, ask on [our issue tracker](https://github.com/centerofci/mathesar/issues/) or [StackOverflow](https://stackoverflow.com/questions/tagged/mathesar)
5. In case you're having trouble formulating a report, reach out [on Matrix](#join-our-community)(#join-our-community)
```

@pavish @kgodey how do these sound?

@kgodey putting this on the wiki makes sense.

2023-03-29 09:16 UTC, dmos62 commented
Closing to be redone on the wiki.

2023-03-29 18:04 UTC, kgodey commented on README.md
> +4. If you think this is a novel problem, ask on one of those platforms or [on Matrix](#join-our-community)
I like the second option with the 5th step. 

Also, do we actually want to be monitoring Stack Overflow? I'd consider removing that in favor of just the issue tracker. I don't have a strong opinion, though.

2023-03-30 09:36 UTC, dmos62 commented on README.md
> +4. If you think this is a novel problem, ask on one of those platforms or [on Matrix](#join-our-community)
@kgodey I don't have a strong opinion either; I think SO has its uses, and I expect people to increasingly use it, but we probably shouldn't actively encourage people to post on it at this time :+1:.

2023-05-29 17:08 UTC, pavish approved these changes
I think this looks good.

2023-07-24 10:53 UTC, dmos62 commented
When I submitted this a few months ago (during GSoC, I think), I was under the impression that our bug report funnels could be improved. Now that some time has passed, I'm not sure that is still true. Anyone that's been dealing with bug reports has input? This isn't exactly documentation, but might be within your domain of interest, @seancolsen.

2023-07-24 11:06 UTC, seancolsen commented
I'm neutral on this PR. Seems fine to me. And I'm not sure if we need it. I'd be okay with merging or closing.

2023-07-24 17:32 UTC, kgodey approved these changes

2023-07-24 17:33 UTC, kgodey commented
I'm merging this, I don't see how this hurts anything and it could help.

2023-07-24 17:36 UTC, merged