Allow data to be copied from Mathesar and pasted elsewhere
centerofci/mathesar pull request #2773
Opened 2023-03-31 15:45 UTC by seancolsen

Fixes #1688

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-04-03 20:54 UTC, seancolsen commented
@rajatvijay I assigned this to you because you asked 1/1 if you could review this.

@pavish I assigned this to you because you're marked as a reviewer on the [usability improvements project](https://wiki.mathesar.org/en/projects/2023-04-usability-improvements.md). There is also some of your code that I've changed which you might like to look over (e.g. `arrayFactory.ts` and related). But if you want to defer review to Rajat, that's fine with me.

2023-04-11 14:07 UTC, pavish requested changes
@seancolsen 

I tried testing this and I noticed that the copy functionality isn't working in Chrome and Safari. It's working in Firefox.

In Safari, selecting cells seems to also select content. I assume `user-select:none` isn't working, I'm not sure, I haven't dug deeper. Either way, the user selected content is being copied due to browser default action, but the selected cells content isn't copied.

I haven't reviewed the PR yet.

2023-04-11 15:01 UTC, seancolsen commented
@pavish thanks for catching that.

> In Safari, selecting cells seems to also select content.

I'm reproducing this in the latest `develop`, so I opened #2806 for it.

I'll work on the issue with copy not behaving correctly in Chrome/Safari.

2023-04-18 17:21 UTC, pavish commented on mathesar_ui/src/components/sheet/SheetClipboardHandler.ts
> +    return '';
We should probably document `null` values would be copied as `''` in the clipboard specs.

2023-04-18 17:53 UTC, pavish approved these changes
@seancolsen Looks good overall, nice work on this.

There are a couple concerns:
* This still doesn't work on Safari. While the text selection bug is still there, the columns which are selected aren't being copied. A single active cell isn't being copied as well. 
   - Please create an issue to track this.
* We need to quote the values wherever necessary, and when we do that, we have to make sure we escape the quotes within them. I saw the comment on the description, please create a separate issue to track this.

Please go ahead and merge once the issues are created.

2023-04-18 17:53 UTC, pavish commented on mathesar_ui/src/components/cell-fabric/data-types/arrayFactory.ts
> +        }
The values can contain commas. We need to quote values here and escape quotes within the strings.

2023-04-18 17:53 UTC, pavish commented on mathesar_ui/src/components/cell-fabric/data-types/string.ts
> +  getDisplayFormatter: () => String,
We need to quote strings which have `\t` characters. This applies for all types.

2023-04-18 18:10 UTC, pavish commented
Followups:
* https://github.com/centerofci/mathesar/issues/2811
* https://github.com/centerofci/mathesar/issues/2812
* https://github.com/centerofci/mathesar/issues/2806

From @seancolsen:

> The bug with the cell selection and text selection is making it harder to test the clipboard feature. The clipboard feature still works in Safari though. Click one cell to select a cell. Then press an arrow key to select an adjacent cell. Then use your keyboard shortcut to copy the cell value. You should see a toast message at that point.

Fixing https://github.com/centerofci/mathesar/issues/2806 should fix the issue with copying in Safari.

2023-04-18 18:14 UTC, merged