Add `mean` aggregation function
centerofci/mathesar pull request #2916
Opened 2023-06-05 07:32 UTC by Aritra8438

Fixes #2915 

**This pull request adds support for `Mean` aggregation as a transformation step in the data explorer.** 

User will be able to:
- Get Mean of integer columns based on `Group By` clause.
- Get Mean of decimal columns based on `Group By` clause.
---
**Technical details**

I have made the following changes:
- Add `Mean(DBFunction)` class to support sum aggregation
- Add `mean` suffix to the output alias of the aggregated column.
- Add `Mean` to the list of transformation steps in the data explorer.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-06-09 09:07 UTC, mathemancer requested changes
Back end changes look good. To merge, you need to:
- sort out merge conflicts.
- get the front end bit added.

2023-06-14 10:42 UTC, Aritra8438 commented
Hi @mathemancer and @seancolsen. This PR is stacked on #2914, which is again stacked on #2912.

So, the ideal order of merging will be, #2912 -> #2914 -> #2916.

2023-06-14 12:59 UTC, seancolsen approved these changes

2023-06-16 02:54 UTC, mathemancer approved these changes
Nice work as usual!

2023-06-16 03:15 UTC, merged