Add `Peak Month` aggregation function.
centerofci/mathesar pull request #3006
Opened 2023-07-06 13:04 UTC by Aritra8438

Fixes #3004 

This PR adds `Peak Month` aggregation function to the Mathesar UI.

**Technical details**

I have done the following things:
- Add custom PostgreSQL function for `Peak Month` aggregation.
- Add `Peak Month` to the Mathesar UI.
- Add tests for the same.

**Screenshots**

<img width="960" alt="image" src="https://github.com/centerofci/mathesar/assets/64671908/5255566e-f4f9-45cd-bf00-9dbe3acf8020">

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-07-07 07:19 UTC, mathemancer requested changes
Big picture is the same as my previous review. I think the calculations should be less discrete, and open the potential for figuring out the peak _day_ in a year, or peak month, or peak week (Germans would like this).

2023-07-10 17:03 UTC, seancolsen approved these changes
Front end changes look good.

All my concerns from [Peak Day of Week](https://github.com/centerofci/mathesar/pull/3004) apply here as well though.

2023-07-19 05:35 UTC, mathemancer requested changes
Looks great overall! Thanks for the great comments explaining the functions.

The only change I have to request is to remove the casting of output months to strings. They should either be integers, or 2-digit formatted numeric strings (e.g., `'01', '02', '11', '12'`)

2023-07-19 05:35 UTC, mathemancer commented on db/sql/3_msar_custom_aggregates.sql
> +$$ LANGUAGE SQL;
If you'll recall, we decided to keep the months as integers, since these won't be localized.

2023-07-19 05:35 UTC, mathemancer commented on db/sql/3_msar_custom_aggregates.sql
> +  ELSE msar.month_int_to_string(msar.degrees_to_month(atan2d(point_[0],point_[1])))
Please just keep the month as an integer here.

2023-07-20 15:24 UTC, seancolsen approved these changes

2023-07-24 05:24 UTC, mathemancer approved these changes
Okay, this looks good. Thank you!

2023-07-24 05:52 UTC, merged