Fix grouping counts
centerofci/mathesar pull request #353
Opened 2021-07-12 21:19 UTC by eito-fis

Fixes #352

Updates the record endpoint to have proper grouping behaviors.

**Technical details**
Updates the `get_group_counts()` function to create a subquery with the appropriate parameters applied, before grouping on the result. Also updates the limit offset tests and adds a new filtering + grouping test.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-07-12 21:32 UTC, kgodey commented
@eito-fis Please see the new format suggestion in the issue (comma separation of values could be confusing, since values can have commas in them).

2021-07-13 18:48 UTC, kgodey commented on mathesar/pagination.py
> +            group_count = [{"columns": list(cols), "count": count}
@eito-fis On second thought, I think changing this key to `values` instead of `columns` makes more sense, these aren't column names.

2021-07-13 19:31 UTC, kgodey reviewed
@eito-fis I tested this locally by going to `http://localhost:8000/api/v0/tables/2/records/?group_count_by%3D[%22Status%22]` in my browser and I'm getting 

```
    "group_count": {
        "group_count_by": null,
        "results": null
    },
```

It should be returning the group count for the `Status` column, right? Am I accessing the API correctly?

2021-07-13 20:00 UTC, eito-fis commented
> @eito-fis I tested this locally by going to `http://localhost:8000/api/v0/tables/2/records/?group_count_by%3D[%22Status%22]` in my browser and I'm getting
> 
> ```
>     "group_count": {
>         "group_count_by": null,
>         "results": null
>     },
> ```
> 
> It should be returning the group count for the `Status` column, right? Am I accessing the API correctly?

That's strange, running `client.get(f'/api/v0/tables/{table.id}/records/?group_count_by=["Status"]')` in a test returns:
```python
'group_count': {
    'group_count_by': ['Status'],
    'results': [
        {'values': ['Issued'], 'count': 48},
        {'values': ['Application'], 'count': 2}
    ]
}
```
Are the tests passing for you?

2021-07-13 20:19 UTC, kgodey commented
@eito-fis The tests are passing for me. Do you get the same result when you go the URL in your browser?

2021-07-13 20:26 UTC, kgodey commented
@eito-fis I figured out the issue. When I replace the `%3D` with `=`, it works fine. It looks like you'll need to handle URL encoding correctly.

2021-07-13 20:32 UTC, kgodey requested changes
@eito-fis Looks good overall, nice work. Please handle URL encoding correctly and also add a test for it so that we don't break it in the future.

2021-07-13 21:17 UTC, eito-fis commented
@kgodey After looking around a bit, I think this is desired behavior? it seems like [the `=` character is reserved to separate keys and values in the url](https://developers.google.com/maps/url-encoding), and shouldn't be encoded when being used for that purpose.

2021-07-13 21:22 UTC, kgodey commented
@eito-fis I think you're correct. I probably ended up with that URL because I mistyped the query to begin with and my browser got confuse by the `=`. Sorry for the false alarm.

2021-07-13 21:22 UTC, kgodey approved these changes

2021-07-13 21:22 UTC, merged