Delete and rename tables
centerofci/mathesar pull request #354
Opened 2021-07-13 04:16 UTC by eito-fis

Fixes #183, Fixes #186

Adds the `delete_table()` and `rename_table()` functions to `db.tables`.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-07-13 20:51 UTC, kgodey commented on db/tables.py
> +def delete_table(name, schema, engine):
How does this handle references to this table from other tables? e.g. another table might have foreign keys pointing to this one.

2021-07-13 20:51 UTC, kgodey commented on db/tables.py
> +def rename_table(name, schema, engine, rename_to):
Same question about handling references to this table from other tables.

2021-07-14 04:19 UTC, eito-fis commented
Updated tests to handle foreign key cases, and also added the `cascade` and `if_exists` options to the `delete_table` function.

2021-07-14 15:12 UTC, kgodey requested changes
Looks good overall, just one question. Also, since this is entirely `db` focused, I'd like @mathemancer to look at it quickly before merge.

2021-07-14 15:12 UTC, kgodey commented on db/tables.py
> +def delete_table(name, schema, engine, cascade=False, if_exists=False):
If `cascade` is `False`, can you return a list of related items just like with schemas?

2021-07-14 17:37 UTC, mathemancer reviewed
Similarly to schemata, I think we should have a separate endpoint at something like:
```
/api/v0/tables/<table_id>/dependencies/
```
That would return a paginated set of dependent objects.  There could be many, and I think the pagination would be a good idea.  I suggest trying to use the `pg_depends` table (view?) to crawl the dependency graph.  The reason is that it would be highly undesirable to list some but not all dependent objects, since this could give the user false confidence, and result in accidental deletion of objects they don't want to get rid of.

`CASCADE` is an extremely aggressive flag, and care should be taken here.  I.e., `CASCADE` will follow the dependency graph as far as it goes (and as far as permissions allow).

2021-07-14 18:27 UTC, kgodey commented
ll create a separate issue for the list of dependencies and corresponding API. For now, @eito-fis, please update the error message to be generic as @mathemancer suggested in the other issue.

2021-07-14 19:22 UTC, eito-fis commented
Similar update to the schema PR, just modified `delete_table` to raise the original `DependentObjectStillExists` error.

2021-07-14 19:23 UTC, kgodey approved these changes

2021-07-14 20:00 UTC, kgodey commented
I'm going to merge this since @mathemancer didn't request changes.

2021-07-14 20:00 UTC, merged