Bohemia420 668
centerofci/mathesar pull request #680
Opened 2021-09-26 17:58 UTC by bohemia420

sqlalchemy engine's `reflection` was rather found absurd and thought of to be attempted - sqlalchemy only sets True that table's found while looping through the columns, which is redundant at first, and a False Negative, for tables with 0 columns (a scenario we touch when we delete all its columns).

While penning down a separately handled reflection method is great, it might rather be replicating few scores of similar code for one small handling. Thence, either we publish our own modified pypis / choose to install customized wheels/eggss i.e releases of various py packages, 

or keep a `tweaked-site-packaged` wherein we bring in select files/snippets to be replaced/handled separately. Whichever appeals more on being neat. 

p.s: `tweaked-site-packages/sqlalchemy/engine/reflection.py` diff is only towards:

```
found_table = True #False
        cols_by_orig_name = {}
        for col_d in self.get_columns(
            table_name, schema, **table.dialect_kwargs
        ):
            found_table = True

            self._reflect_column(
                table,
                col_d,
                include_columns,
                exclude_columns,
                cols_by_orig_name,
            )

        if not found_table:
            raise exc.NoSuchTableError(table.name)
```

wherein `found_table` can be removed out too (finding it redundant).

2021-09-27 17:35 UTC, kgodey requested changes
I don't think we should maintain a separate version of a single file from SQLAlchemy in our repository, keeping it in sync will be a pain. I recommend opening a bug report instead; they may fix it (or provide a good reason for why it shouldn't be fixed).

2021-09-27 17:42 UTC, bohemia420 commented
@kgodey makes sense, in fact was as well, considering writing to SQLAlchemy instead. They should ideally fix it, `found_table` looks all very redundant, otherwise.

2021-09-27 17:43 UTC, kgodey commented
@bohemia420 Please link the issue here once you open it so that we can keep track of it.

2021-09-30 07:15 UTC, bohemia420 commented
Sure @kgodey , have done that, the issue now stands raised to SQLAlchemy [here](https://github.com/sqlalchemy/sqlalchemy/issues/7117) and have also proposed a PR to help this issue, [here](https://github.com/sqlalchemy/sqlalchemy/issues). My apologies, certainly this issue couldn't have been helped with diverging from origin SQLAlchemy to our own maintained and substituting select/cherrypicked files utterly dangerous - have poured in my thoughts with end-to-end analysis/troubleshooting [here](https://github.com/centerofci/mathesar/issues/668#issuecomment-930894085) #668

2021-09-30 17:50 UTC, kgodey commented
Thanks @bohemia420! I'll close this PR since the issue will hopefully be fixed upstream.

2021-09-30 17:50 UTC, closed without merging