Non unicode file parsing fix
centerofci/mathesar pull request #688
Opened 2021-09-30 18:13 UTC by silentninja

Fixes centerofci/mathesar#421

Enables parsing of non-unicode files by finding the correct encoding using chardet(charset-normalizer if installed).
## Checklist
 
- [ X ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ X ] My pull request targets the `master` branch of the repository
- [ X ] My commit messages follow [best practices][best_practices].
- [ X ] My code follows the established code style of the repository.
- [ X ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ X ] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-09-30 18:28 UTC, silentninja commented
Not sure where the documentation code is hosted.

Would like to inform users that charset-normalizer can be installed optionally for better detection than the default chardet.

2021-09-30 18:30 UTC, silentninja commented
I have used the charset library which is a dependency of clevercsv which is the actual dependency we use. Not really a good practice since it is not explicitly declared. Charset is backward compatible with chardet, so should we use it by default, or should charset be preferred.

2021-09-30 19:11 UTC, kgodey requested changes
This looks good, nice work! Please add the note about charset normalizer/chardet to `README.md` for now since we do not have more detailed product documentation anywhere else.

Some minor changes requested for tests. Also, the checklist in the PR description should work if you remove the spaces between the `[`/`]` and the `X`.

2021-09-30 19:11 UTC, kgodey commented on mathesar/tests/api/test_data_file_api.py
> +    with open(file, 'rb') as f:
Could you use a more verbose variable name instead of `f`?

2021-09-30 19:11 UTC, kgodey commented on mathesar/tests/api/test_data_file_api.py
> +def test_data_file_create_non_unicode_file(client):
Shouldn't this also take the `non_unicode_csv_filename` fixture as an argument?

2021-09-30 19:11 UTC, kgodey commented on mathesar/tests/api/test_data_file_api.py
> +    file = 'mathesar/tests/data/non_unicode.csv'
Once you pass in the fixture, you won't need this line.

2021-10-04 22:01 UTC, kgodey requested changes
This is looking good. I found an issue during local testing, plus one code style comment.

2021-10-04 22:01 UTC, kgodey commented on db/records/operations/insert.py
> +            encoding = f"sql_{encoding}" if encoding == "ascii" else encoding
We need to ensure the encoding option is supported by Postgres. Here's the list of supported options: https://www.postgresql.org/docs/9.3/multibyte.html

I tried with a CSV encoded with `utf_16_le`, which failed with the following error:

```
argument to option "encoding" must be a valid encoding name
LINE 1: ...) FROM STDIN CSV HEADER DELIMITER E','  QUOTE '"' ENCODING '..
```

Here's a test CSV you can use: [movies.csv](https://github.com/centerofci/mathesar/files/7281554/movies.csv)

FYI, the encoding is only detected correctly with `charset-normalizer` installed.

2021-11-08 17:17 UTC, kgodey requested changes
Looks good overall, some minor changes requested. Merge conflicts also need to be resolved.

2021-11-08 17:17 UTC, kgodey commented on db/encoding_utils.py
> +                                 }
This is what I was suggesting, I think it's more readable.

```suggestion
_SQL_COMPATIBLE_ENCODINGS_MAP = {
    'iso8859-15': ('iso8859-15', 'LATIN9'),
    'cp1253': ('cp1253', 'WIN1253'),
    'iso8859-16': ('iso8859-16', 'LATIN10'),
    'iso8859-4': ('iso8859-4', 'LATIN4'),
    'gbk': ('gbk', 'GBK'),
    'cp1250': ('cp1250', 'WIN1250'),
    'gb18030': ('gb18030', 'GB18030'),
    'cp949': ('cp949', 'UHC'),
    'iso8859-14': ('iso8859-14', 'LATIN8'),
    'cp1251': ('cp1251', 'WIN1251'),
    'shift_jis_2004': ('shift_jis_2004', 'SHIFT_JIS_2004'),
    'gb2312': ('gb2312', 'EUC_CN'),
    'cp1255': ('cp1255', 'WIN1255'),
    'johab': ('johab', 'JOHAB'),
    'cp1257': ('cp1257', 'WIN1257'),
    'iso8859-5': ('iso8859-5', 'ISO_8859_5'),
    'euc_jis_2004': ('euc_jis_2004', 'EUC_JIS_2004'),
    'iso8859-13': ('iso8859-13', 'LATIN7'),
    'utf-8': ('utf-8', 'UTF8'),
    'big5': ('big5', 'BIG5'),
    'iso8859-2': ('iso8859-2', 'LATIN2'),
    'iso8859-3': ('iso8859-3', 'LATIN3'),
    'cp1256': ('cp1256', 'WIN1256'),
    'iso8859-7': ('iso8859-7', 'ISO_8859_7'),
    'shift_jis': ('shift_jis', 'SJIS'),
    'cp866': ('cp866', 'WIN866'),
    'cp1254': ('cp1254', 'WIN1254'),
    'cp874': ('cp874', 'WIN874'),
    'iso8859-6': ('iso8859-6', 'ISO_8859_6'),
    'iso8859-1': ('iso8859-1', 'LATIN1'),
    'cp1258': ('cp1258', 'WIN1258'),
    'iso8859-9': ('iso8859-9', 'LATIN5'),
    'iso8859-8': ('iso8859-8', 'ISO_8859_8'),
    'euc_jp': ('euc_jp', 'EUC_JP'),
    'euc_kr': ('euc_kr', 'EUC_KR'),
    'cp1252': ('cp1252', 'WIN1252'),
    'iso8859-10': ('iso8859-10', 'LATIN6'),
    'utf-32-be': ('utf-8', 'utf-8'),
    'utf-8-sig': ('utf-8', 'utf-8'),
    'utf-16-be': ('utf-8', 'utf-8'),
    'utf-32': ('utf-8', 'utf-8'),
    'utf-32-le': ('utf-8', 'utf-8'),
    'utf-16-le': ('utf-8', 'utf-8'),
    'ascii': ('utf-8', 'utf-8'),
    'utf-16': ('utf-8', 'utf-8'),
    'utf-7': ('utf-8', 'utf-8')
}
```

2021-11-08 17:17 UTC, kgodey commented on README.md
> +By default [Chardet](https://github.com/chardet/chardet) is used for parsing csv in order to maintain compatability with other libraries, but if you need faster detection or wider encoding support [C
This documentation needs to be updated since we're using `charset-normalizer`.

2021-11-10 15:14 UTC, kgodey approved these changes
Looks good, thanks!

2021-11-10 16:07 UTC, merged