Enable TypeScript strict mode
centerofci/mathesar pull request #826
Opened 2021-11-17 01:25 UTC by seancolsen

Fixes #619

## Checklist

- [] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [] My pull request targets the `master` branch of the repository
- [] My commit messages follow [best practices][best_practices].
- [] My code follows the established code style of the repository.
- [] I added tests for the changes I made (if applicable).
- [] I added or updated documentation (if applicable).
- [] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-11-17 01:30 UTC, seancolsen commented
@pavish Here's a quick beginning to the process of making our typing more strict.

Making these changes across the codebase will be easy. We just need some clarity on on [how to deal with null vs undefined](https://github.com/centerofci/mathesar/discussions/825). The diff in 1776359f708ddf43613c1818847ecb1841e6698e will give you a sense of the kinds of changes we'll need to make. In lots of these scenarios, we can choose to resolve ambiguity towards `null` or towards `undefined`. I'd like to get some clarity on a general pattern to follow before continuing. Please weigh in within the discussion.

2021-11-17 19:59 UTC, pavish commented
@seancolsen I've responded to the discussion. My preference would be to use `undefined` and only use `null` when serialization is required.

2021-12-23 16:42 UTC, seancolsen commented
@pavish this is ready for review now.

I kept this same PR in-place but stripped out all the complex changes, leaving only the simple ones that we should be safe to merge now, with strict mode off.

I still have the rest of my changes locally and will build another PR with them later to continue working towards closing #619.

2022-01-14 17:20 UTC, pavish commented
@seancolsen Could you please update this PR to resolve the merge conflicts? I'd like to merge this in before the other current open PRs at the time of this comment.

2022-01-17 21:02 UTC, pavish requested changes
@seancolsen The PR looks good for the major part.

There is one major bug that needs to be fixed: Add schema modal does not open. Once this bug is fixed, we can merge this PR.

2022-01-18 13:40 UTC, seancolsen commented on mathesar_ui/src/component-library/file-upload/FileUpload.svelte
> +<div class="file-upload" class:inprogress={fileUploads && fileUploads.length > 0}>
Not sure what I was thinking there :thinking: 

Thanks for pointing this out. Fixed in da834c8f216863153309d8030518f8abfbb6032a

2022-01-18 13:40 UTC, seancolsen commented on mathesar_ui/src/pages/schemas/Schemas.svelte
> +{#if isAddModalOpen && activeSchema}
My bad thanks for catching this. Fixed in fe380c318a176f7bcf2cb9cdb87b0e4b4cdf1c3c where I simplified `AddEditSchema` a bit.

2022-01-18 13:40 UTC, seancolsen commented on mathesar_ui/src/pages/schemas/AddEditSchema.svelte
> +  export let schema: SchemaEntry;
Also fixed in fe380c318a176f7bcf2cb9cdb87b0e4b4cdf1c3c

2022-01-18 13:41 UTC, seancolsen commented
@pavish ready for re-review

2022-01-18 22:21 UTC, pavish approved these changes

2022-01-18 22:21 UTC, pavish commented
@seancolsen Looks good to me.

2022-01-18 22:44 UTC, merged