DRF test client request parameters
centerofci/mathesar pull request #841
Opened 2021-11-24 07:43 UTC by andruwwwka

Fixes #813.

Use correct django-rest-framework test client parameters when sending json body payload

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-11-24 18:34 UTC, kgodey commented
@silentninja Assigning this to you for review, please feel free to pull in others if needed.

2021-11-30 19:02 UTC, silentninja commented
@andruwwwka Thanks for the PR. I think it would be better to specify `json` as the default request format and use `format` option for the requests that are multipart. @kgodey I would appreciate your comments on this

2021-12-03 19:44 UTC, kgodey commented
@silentninja That sounds fine to me, it would reduce boilerplate code.

2021-12-03 20:32 UTC, andruwwwka commented
@silentninja Hi! I update the PR.

2021-12-06 11:55 UTC, silentninja requested changes
`get` data objects should be JSON string rather than the string representation from `f` string conversion as the backend expects a JSON object and `f` string outputs a urlencoded string which is not a valid JSON object. Moreover, test cases could fail if the object has nested objects as URL encoded objects won't have a clean conversion, so I think it is better to stick with json encoded string

2021-12-06 11:55 UTC, silentninja commented on mathesar/tests/api/test_record_api.py
> +    data = {"group_count_by": ["Center"]}
This should be a json string.

2021-12-06 14:01 UTC, andruwwwka commented
@silentninja I have corrected the code according to your comment

2021-12-06 14:05 UTC, silentninja approved these changes

2021-12-06 14:05 UTC, merged

2021-12-06 14:31 UTC, kgodey commented
Thanks for your work on this, @andruwwwka!